name: build-projects

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x'
        
    - name: Restore dependencies
      run: dotnet restore SiteUtils/SiteUtils.sln
      
    - name: Build all projects
      run: dotnet build SiteUtils/SiteUtils.sln --configuration Release --no-restore
      
    - name: Test run BuildNavigation
      run: dotnet run --project SiteUtils/BuildNavigation/BuildNavigation.csproj --configuration Release --no-build
      
    - name: Test run NameTransformer (help)
      run: dotnet run --project SiteUtils/NameTransformer/NameTransformer.csproj --configuration Release --no-build || true
